%token <STRING> V_IDENTIFIER
%token <STRING> V_ARCHETYPE_ID
%token <STRING> V_LOCAL_TERM_CODE_REF
%token <STRING> V_DADL_TEXT V_CADL_TEXT V_ASSERTION_TEXT
%token <STRING> V_VERSION_STRING

%token SYM_ARCHETYPE SYM_CONCEPT SYM_SPECIALIZE
%token SYM_DEFINITION SYM_LANGUAGE
%token SYM_DESCRIPTION SYM_ONTOLOGY SYM_INVARIANT
%token SYM_ADL_VERSION SYM_IS_CONTROLLED

%%

input: archetype	
	| error

archetype: arch_identification 
	   	arch_specialisation 
		arch_concept 
		arch_language 
		arch_description 
		arch_definition 
		arch_invariant
		arch_ontology


arch_identification: arch_head V_ARCHETYPE_ID 
	| SYM_ARCHETYPE error

arch_head: SYM_ARCHETYPE 
	| SYM_ARCHETYPE arch_meta_data

arch_meta_data: '(' arch_meta_data_items ')'

arch_meta_data_items: arch_meta_data_item
	| arch_meta_data_items ';' arch_meta_data_item

arch_meta_data_item: SYM_ADL_VERSION '=' V_VERSION_STRING
	| SYM_IS_CONTROLLED

arch_specialisation: -- empty is ok
	| SYM_SPECIALIZE V_ARCHETYPE_ID 
	| SYM_SPECIALIZE error

arch_concept: SYM_CONCEPT V_LOCAL_TERM_CODE_REF 
	| SYM_CONCEPT error

arch_language: -- empty is ok for ADL 1.4 tools
	| SYM_LANGUAGE V_DADL_TEXT
	| SYM_LANGUAGE error

arch_description: -- no meta-data ok
	| SYM_DESCRIPTION V_DADL_TEXT 
	| SYM_DESCRIPTION error

arch_definition:	SYM_DEFINITION V_CADL_TEXT	
	| SYM_DEFINITION error

arch_invariant: -- no invariant ok
	| SYM_INVARIANT V_ASSERTION_TEXT
	| SYM_INVARIANT error

arch_ontology: SYM_ONTOLOGY V_DADL_TEXT
	| SYM_ONTOLOGY error

