require 'rubygems'
Gem::manage_gems
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'yaml'

task :default => [:test]

desc "Whole Unit tests"
task 'test' => ['test:am', 'test:rm', 'test:assumed_library_types']
Rake::TestTask.new('test:am') do |t|
  t.libs = ["lib"]
  t.pattern = ['tests/test_archetype_model.rb']
  t.warning = true
  t.verbose = true
end

Rake::TestTask.new('test:rm') do |t|
  t.libs = ["lib"]
  t.pattern = ['tests/test_reference_model.rb']
  t.warning = true
  t.verbose = true
end

Rake::TestTask.new('test:assumed_library_types') do |t|
  t.libs = ["lib"]
  t.pattern = ['tests/test_assumed_library_types.rb']
  t.warning = true
  t.verbose = true
end


gem_spec = Gem::Specification.new do |s|
  s.name = 'openehr_models'
  s.author = 'Shinji KOBAYASHI, Akimichi TATSUKAWA'
  s.version = '0.0.1'
  s.summary = 'OpenEHR models'
  s.email = 'openehr-jp@openehr.jp'
  s.test_files = FileList['tests/test_*.rb', '*.adl']
  candidates = Dir.glob("{am,rm,docs,tests}/**/*") + FileList['COPYING', 'Rakefile','am.rb','assumed_library_types.rb','rm.rb']
  s.files = candidates.delete_if do |item|
    item.include?(".svn") || item.include?("rdoc")
  end
#  s.require_paths += [".","am","rm"]
  s.require_path = "."
  s.has_rdoc = true
#  s.extra_rdoc_files = ["README"]
end


Rake::GemPackageTask.new(gem_spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end

#CLOBBER.include('rdoc')
#CLEAN.include('lib/*.output', 'log/*.log')




### Local Variables:
### mode:ruby
### mode:font-lock
### comment-column:0
### comment-start: "### "
### comment-end:"" 
### End:


